name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.0.6
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/icon/orders.png
    - assets/images/icon/kefus.png
    - assets/images/icon/mes.png
    - assets/images/icon/me.png
    - assets/images/icon/home.png
    - assets/images/icon/scan.png
    - assets/images/icon/order.png
    - assets/images/icon/kefu.png
    - assets/images/icon/homes.png
    - assets/images/img/SwImg1.jpg
    - assets/images/img/bg.png
    - assets/images/img/cloth.png
    - assets/images/img/cloth1.png
    - assets/images/img/dry.png
    - assets/images/img/dry1.png
    - assets/images/img/shoe.png
    - assets/images/img/shoe1.png
    - assets/images/icon/arrowdown.png
    - assets/images/icon/shop.png
    - assets/images/icon/time.png
    - assets/images/img/whitebg.png
    - assets/images/img/bluebg.png
    - assets/images/icon/machine.png
    - assets/images/icon/machines.png
    - assets/images/icon/machine1.png
    - assets/images/icon/machine2.png
    - assets/images/icon/dom.png
    - assets/images/icon/tu.png
    - assets/images/icon/arrowright.png
    - assets/images/icon/lock.png
    - assets/images/icon/wallet.png
    - assets/images/icon/about.png
    - assets/images/icon/more.png
    - assets/images/icon/clear.png
    - assets/images/icon/bill.png
    - assets/images/icon/act.png
    - assets/images/icon/dollor.png
    - assets/images/img/tx.png
    - assets/images/icon/pen.png
    - assets/images/icon/kuai.png
    - assets/images/icon/edit.png
    - assets/images/img/mebg.png
    - assets/images/img/txs.png
    - assets/images/icon/tu2.png